### PR TITLE
feat: newegg realtime api

### LINKED ISSUE #643: Numerous Newegg false positives
### Description

Lots of (seemingly) false positives on Newegg for EVGA 3080 FTW3 Ultra this morning (over the past hour so far, and ongoing). Visiting the product page, the “add to cart” link does sometimes appear, but attempting to add to cart yields an error modal “Oops...looks like we have encountered some problem on our end. Please try again in a little while.”; in the Newegg app, this manifests as “added to cart successfully”, but cart is empty—using Apple Pay on the product page instead of “add to cart” yields an error modal “sold out”.

I’m running latest commit 2fc584bdbdb978b5a57bc8660c2a1d3c5be0a81b. Running with headless and low bandwidth enabled.

### Possible solution

Perhaps clicking add to cart when in stock and check for error.

### LINKED ISSUE #646: Newegg API Support
Newegg has a public api for each product. Example of 3080 ftw3 ultra:
https://www.newegg.com/product/api/ProductRealtime?ItemNumber=14-487-518

If you search "Instock" , you will find that it is not in stock and the stock amount...which in this case:
sfLMG8d

This is a realtime stock checker and would give more accurate results than the current check for "add to cart" as it tends to bug out. Item numbers can sometimes be found in the urls or if you have developer tools/network open and refresh the page, you can find by searching "ItemNumber":
nshrnUd

And will be shown in the first link.

I would be happy to get the newegg-api.ts setup with all the api urls if this is something that sounds like a good idea.
"LocalAvail" is the correct variable for current inventory stock.

### PR DESCRIPTION
**Pull request by jbwilliams1**
### Description

Added realtime inventory lookup for Newegg cards

Resolves #646 
Resolves #643 

### Testing

Used an in-stock card for the test series, validated it worked on an in-stock and out of stock card. Runs normally on out-of-stock cards

### New dependencies

None (well, node-fetch, but it's bundled in)

### CODE REVIEW

**Comment by jbwilliams1** [comment]
I don't program in node, and generally write code in Rust... so not overly familiar with nodejs

Whatever you need me to fix let me know.

**Comment by jef** [comment]
> I don't program in node/javascript anymore, and generally write code in Rust or Python

Join the club 😆 I'll go over this later today. Thanks for the hard work on this one!

**Comment by jbwilliams1** [comment]
Sorry for all of the commits, I was annoyed by the linter not passing :)

**Comment by jef** [comment]
No problem. I appreciate you sticking through it 😀

**Review by jef — APPROVED** [review]
This is awesome! I appreciate you putting in this work. Let's see how it goes!

**Comment by jef** [comment]
I went ahead and fixed up some dependency conflicts, hope you don't mind. Let's get this in here!

**Pull request merged**
