### PR TITLE
fix(filterBrandsSeriesModels): always loop all stores

### PR DESCRIPTION
**Pull request by Doridian**
### Description

This should always have all possible combinations. And also set min/max page sleep to sane defaults.

### CODE REVIEW

**Comment by jef** [comment]
Can you explain this a little more to me? I'd figure we wouldn't want to do extra work that isn't needed.

**Comment by Doridian** [comment]
It doesn't really do any more work. Unless you mean adding some strings to `Set`s (which is just done once on startup, and makes the WebUI list all cards, regardless of which stores you picked, which is correct).
Basically, the issue is without this in place, some stores have `undefined` as their minSleep/maxSleep. Which, due to the `setTimeout` used, can lead to an absolute mess in terms of CPU load. (`undefined` or `NaN` in `setTimeout` basically means "re-run immediately").

**Comment by Doridian** [comment]
Essentially, what I'm saying is that without at least
```
		if (store.minPageSleep === undefined) {
			store.minPageSleep = defaultStoreData.minPageSleep;
		}

		if (store.maxPageSleep === undefined) {
			store.maxPageSleep = defaultStoreData.maxPageSleep;
		}
```
being run on every store (no matter if enabled or not), if you don't enable all stores, the process starts consuming way more CPU than it should just ramming infinite loops.

**Comment by jef** [comment]
Oh man, this really needs a refactoring... I we shouldn't even be evaluating these stores. They should be options in the UI, but not evaluated.

Such a shame. Thanks for the fix Doridian.

**Review by jef — APPROVED** [review]

**Comment by heypiotr** [comment]
FWIW, I "fixed" this in a different way in my local version:

```diff
diff --git a/src/index.ts b/src/index.ts
index 6c377fa..0a12cdc 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -7,7 +7,7 @@ import {logger} from './logger';
 import puppeteer from 'puppeteer-extra';
 import resourceBlock from 'puppeteer-extra-plugin-block-resources';
 import stealthPlugin from 'puppeteer-extra-plugin-stealth';
-import {storeList} from './store/model';
+import {getStores} from './store/model';
 import {tryLookupAndLoop} from './store';
 
 puppeteer.use(stealthPlugin());
@@ -55,7 +55,7 @@ async function main() {
                headless: config.browser.isHeadless
        });
 
-       for (const store of storeList.values()) {
+       for (const store of getStores().values()) {
                logger.debug('store links', {meta: {links: store.links}});
                if (store.setupAction !== undefined) {
                        store.setupAction(browser);
```

`storeList` is all the stores, `getStores()` is the filtered list.

**Comment by jef** [comment]
@heypiotr, just seeing this now. Thanks for the recommendation!

**Pull request merged**
