### PR TITLE
refactor: easier comparables, fix audits

### LINKED ISSUE #620: Stores showing up that I'm not searching for
Im running a snatcher on a VM and I keep getting these messages. It says no store links found but i only have  bestbuy, amazon, newegg, newegg-ca, bestbuy-ca, asus.

**[5:03:27 PM] info :: ℹ selected stores: bestbuy, amazon, newegg, newegg-ca, bestbuy-ca, asus
[5:03:27 PM] info :: ℹ selected models: ftw3, ftw3 ultra, xc3 black, xc3, xc3 ultra, tuf, tuf oc, ventus 3x, ventus 3x oc, founders edition
[5:03:27 PM] info :: ℹ selected series: 3080
[5:03:28 PM] warn :: ✖ in order to receive sms alerts, email notifications must also be configured
[5:03:35 PM] warn :: ✖ [amazon-uk] [setup (3080)] :: NO STORE LINKS FOUND
[5:03:35 PM] warn :: ✖ [amazon-uk] [setup (3080)] :: NO STORE LINKS FOUND
[5:03:37 PM] warn :: ✖ [novatech] [setup (3080)] :: NO STORE LINKS FOUND
[5:03:37 PM] info :: ✖ [bestbuy-ca] [msi (3080)] ventus 3x :: OUT OF STOCK
[5:03:38 PM] warn :: ✖ [box] [setup (3080)] :: NO STORE LINKS FOUND
[5:03:39 PM] info :: ✖ [newegg] [asus (3080)] tuf :: OUT OF STOCK
[5:03:40 PM] info :: ✖ [aria] [setup (3080)] :: FOUND 4 STORE LINKS
[5:03:41 PM] info :: ✖ [bestbuy-ca] [evga (3080)] xc3 ultra :: OUT OF STOCK**

### PR DESCRIPTION
**Pull request by jef**
### Description

- Fixes #620
- Related to #600
	- This will go in a later refactor
	- For now, I am putting the link builder in debug mode
- Bumps node version to 15.0.1
- Removes `rimraf` from `build` task
- `npm audit` now has 0 vulnerbilities
- Fixes issue with Web UI not saving settings

### CODE REVIEW

**Comment by Doridian** [comment]
This PR will work, however from what I can see, if you were to start with a certain store disabled and then enable it in WebUI, the store would not have any links defined.

Also if you do this, you should do
`stores.set(storeData.name, store);`
and put it inside the `if (store) {` to avoid putting blank/undefined stores into the `stores` map.

**Comment by jef** [comment]
> the store would not have any links defined.

I understand what you're saying, but I don't see how. Could you elaborate on this?

**Comment by Doridian** [comment]
Sure. I haven't 100% validated this, but basically here is what I'm thinking.

The change https://github.com/jef/nvidia-snatcher/pull/614/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L58-R58
pretty much  makes it only loop over enabled stores when it runs that codepath (as `getStores()` only contains stores defined in the config, and thus enabled).
So if a store is not enabled while snatcher starts up, that codepath won't run ever.
This means, there will be no loop started for the store, and the startupAction won't run for the store.

**Comment by jef** [comment]
I see in your code now within the `html` file. It's directly utilizing the `config.store.stores` as we talked about. Okay, in that case, perhaps I do similar function call outside of the config and use it there. Or write up an observer. Either way I suppose would work.

I think overall, some of this stuff could use some extra love, but I really appreciate your feedback!

**Comment by jef** [comment]
Okay, I updated the `handleAPI()` function to `updateStores()` when the config gets updated. This should resolve that issue.

Granted, this solution isn't ideal and there is a better way to do this entirely, but this should at least bandage this up until we refactor some of this config.

**Comment by jef** [comment]
Okay, I see your point as well. We never go over that loop of stores again, regardless of where it's coming from.

I'm going to update the place we need to, along with some other things. This could _really_ use some TLC...

**Comment by jef** [comment]
Gonna merge this in later if there aren't any comments! Thanks for the help @Doridian.

**Pull request merged**
