### PR TITLE
feat: Add PagerDuty Integration

### PR DESCRIPTION
**Pull request by HeavenFox**
### Description

Many engineers and operations people use PagerDuty to get paged. This PR adds support for that, so one can get a strong notification when a card gets in stock day or night, overriding any Do Not Disturb setting.

### Testing

Tested with my personal PagerDuty account

Create a service and add integration with the Events API v2. Add the integration key to the .env file. 

IMG_5868 2

### New dependencies
node-pagerduty

### CODE REVIEW

**Comment by jef** [comment]
PagerDuty haunts me...

**Review by jef — APPROVED** [review]
Great contribution. Thanks!

**Comment by jef** [comment]
Lastly, before I merge; do you mind updating the `README` to include your contribution?

**Comment by HeavenFox** [comment]
Thanks for the reminder! Just updated README

**Review by jef — APPROVED** [review]

**Comment by c0ns0le** [comment]
small note, the pagerduty referenced in this merge has a dep which needs to be updated for npm-user-validate

                       === npm audit security report ===               
                                                                       
                                                                       
                                 Manual Review                         
             Some vulnerabilities require your attention to resolve    
                                                                       
          Visit https://go.npm.me/audit-guide for additional guidance  
                                                                       
                                                                       
  Low             Regular Expression Denial of Service                 
                                                                       
  Package         npm-user-validate                                    
                                                                       
  Patched in      >=1.0.1                                              
                                                                       
  Dependency of   node-pagerduty                                       
                                                                       
  Path            node-pagerduty > npm > npm-user-validate             
                                                                       
  More info       https://npmjs.com/advisories/1572

**Comment by jef** [comment]
I did notice this and resolved all but this audit. Probably will need to notify the owner and make a PR here: https://github.com/kmartin-215/node-pagerduty

**Comment by veev-code** [comment]
@HeavenFox Thanks for offering this support. Just out of curiosity, is there anything similar to PagerDuty if I just want alarm-like notifications? PagerDuty seems to require a subscription and only offers a 14 day free trial.

**Comment by jef** [comment]
Fixed here https://github.com/kmartin-215/node-pagerduty/pull/25

**Comment by jef** [comment]
> @HeavenFox Thanks for offering this support. Just out of curiosity, is there anything similar to PagerDuty if I just want alarm-like notifications? PagerDuty seems to require a subscription and only offers a 14 day free trial.

I think your best bet it just setting up custom notifications from an email address or SMS or any of the other notification services

**Comment by veev-code** [comment]
> I think your best bet it just setting up custom notifications from an email address or SMS or any of the other notification services

@jef Makes sense, thanks. I'm primarily relying on Gmail on an iPhone. Any idea how to setup an alarm-like custom notification there?

**Comment by HeavenFox** [comment]
> > I think your best bet it just setting up custom notifications from an email address or SMS or any of the other notification services
> 
> @jef Makes sense, thanks. I'm primarily relying on Gmail on an iPhone. Any idea how to setup an alarm-like custom notification there?

Your best bet might be to use some kind of phone integration, and enable Emergency Bypass for the phone number, if you want to get woken up in the middle of the night.
BTW I got woken up in the middle of the night several times. It's all false positive.

**Pull request merged**
