### PR TITLE
chore(notebooksbilliger): add more FE links

### PR DESCRIPTION
**Pull request by ElegyD**
### Description

Notebooksbilliger created another article page for each Founders Edition series.
This adds the new links for the 3070, 3080, and 3090 FE.

### Testing

I temporarily added the url to the end of buildProductString to verify it is looking up multiple links of the same card on one site.
This may could further be improved by allowing an array of url's in the Link model. But that would need more changes.

### CODE REVIEW

**Comment by ElegyD** [comment]
Actually... we might need another solution. notebooksbilliger.de said they update the link when new cards are available.
https://twitter.com/nbbilliger/status/1322188042262687744
> Der Bestell-Link wird aktualisiert, sobald neue Karten verfügbar sind.

Translates to:
> The order link will be updated as new cards are available.


So when new cards are available, the "Buy" button on the Nvidia site will have the new link to notebooksbilliger.de.
Maybe we shouldn't deprecate nvidia yet for us non-US customers?

**Comment by jef** [comment]
> So when new cards are available, the "Buy" button on the Nvidia site will have the new link to notebooksbilliger.de.
Maybe we shouldn't deprecate nvidia yet for us non-US customers?

I'll probably work on this: https://github.com/jef/nvidia-snatcher/issues/673#issuecomment-721408848

**Comment by jef** [comment]
As for your change, is it accurate to merge in?

**Comment by ElegyD** [comment]
> I'll probably work on this: [#673 (comment)](https://github.com/jef/nvidia-snatcher/issues/673#issuecomment-721408848)

Ah, sounds good!

> As for your change, is it accurate to merge in?

Yeah sure.

**Review by jef — APPROVED** [review]

**Comment by jef** [comment]
Sounds good! Thanks!

**Pull request merged**
