### PR TITLE
chore(naming): Actually rename the function, not just the import

### PR DESCRIPTION
**Pull request by Doridian**
### Description

After my PR was merged, I saw that VSCode did a silly thing and renamed the import instead of the function. This fixes that.

### CODE REVIEW

**Comment by jef** [comment]
Haha, sorry :( I didn't see this. I beat you too it. Thanks for the contribution!!!

Whats your Discord name?

**Comment by Doridian** [comment]
My discord is `Doridian#1337`

**Comment by jef** [comment]
This you? 
image

**Comment by Doridian** [comment]
> My discord is `Doridian#1337`

^

**Comment by Doridian** [comment]
No, not part of the Discord. The invite link on the repo doesn't work.

**Comment by jef** [comment]
https://discord.gg/wfvYzZ8

Will update README.

Thanks!

**Pull request closed without merging**
