### PR TITLE
feat: add ability to send SMS to multiple phone numbers

### PR DESCRIPTION
**Pull request by GRINSPANKER13**
### Description

Updates #446 

### Testing

Same as original pull request

### CODE REVIEW

**Comment by GRINSPANKER13** [comment]
> Closing in favor of #446. There isn't any difference and none of the issues were addressed.
> 
> Sorry and thanks!

The issues you addressed in #446 were changed in my update to it.

**Comment by jef** [comment]
> > Closing in favor of #446. There isn't any difference and none of the issues were addressed.
> > Sorry and thanks!
> 
> The issues you addressed in #446 were changed in my update to it.

https://github.com/jef/nvidia-snatcher/pull/446/files#r499274949
https://github.com/jef/nvidia-snatcher/pull/446/files#r499275105
https://github.com/jef/nvidia-snatcher/pull/446/files#r499275212

I don't see the changes. Maybe you forgot to push?

**Comment by GRINSPANKER13** [comment]
> > > Closing in favor of #446. There isn't any difference and none of the issues were addressed.
> > > Sorry and thanks!
> > 
> > 
> > The issues you addressed in #446 were changed in my update to it.
> 
> https://github.com/jef/nvidia-snatcher/pull/446/files#r499274949
> https://github.com/jef/nvidia-snatcher/pull/446/files#r499275105
> https://github.com/jef/nvidia-snatcher/pull/446/files#r499275212
> 
> I don't see the changes. Maybe you forgot to push?

Yes, I forgot to push the changed, my fault.

**Comment by jef** [comment]
No problem. Feel free to push and we can reopen!

**Comment by GRINSPANKER13** [comment]
> No problem. Feel free to push and we can reopen!

So I pushed it, but the branch was far behind the main. I screwed up on my end and ended up having to re-branch and re-do the changes. The branch is still under "feature/add-multi-sms" but it is not the original branch. Should I open a new pull request or will the changes sync with this one?

**Comment by jef** [comment]
> Should I open a new pull request or will the changes sync with this one?

It should sync with this one.

**Pull request closed without merging**
