### PR TITLE
fix(notifications): twilio client creation

### LINKED ISSUE #348: Unconfigured Twilio causes error
### Description

Issue caused by #344 

```
node_modules/twilio/lib/rest/Twilio.js:130
    throw new Error('username is required');
          ^
Error: username is required
    at new Twilio (node_modules/twilio/lib/rest/Twilio.js:130:11)
    at Object.initializer [as default] (node_modules/twilio/lib/index.js:9:10)
    at Object.<anonymous> (src/notification/twilio.ts:8:22)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module.m._compile (node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
```
### Possible solution

~~Making the twilio integration run conditionally based on the existence of `TWILIO_ACCOUNT_SID`.~~ Turns out the solution was to wait until invocation of `sendTwilioMessage` to create the client

### PR DESCRIPTION
**Pull request by miralize**
### Description
Fixes #348 

### Testing
Ran on my machine

### CODE REVIEW

**Comment by dyndragon** [comment]
I also tested this, seems to work fine.

**Comment by JeffBuss** [comment]
Can confirm this fixes the issue

**Comment by jef** [comment]
thank you. was just about to fix. got dm'd. thank you!!!!!!!!!

**Review by jef — APPROVED** [review]

**Comment by jef** [comment]
Not idea to create a client over and over, but will fix in a chore later.

**Pull request merged**
