### PR TITLE
chore(store): filter amazon third party vendors

### PR DESCRIPTION
**Pull request by jef**
### Description

- Filters third party vendors from Amazon and getting outrageous pricing
- Change Store objects properties for ordering

### CODE REVIEW

**Review by admon84 — APPROVED** [review]
Thanks for reordering some of the change I made.  I'll give more attention to ordering in future contributions.  The changes look good to me

**Review by Doridian — DISMISSED** [review]
The refactor will likely clash with the hotfix https://github.com/jef/nvidia-snatcher/pull/124 so maybe incorporate it right into this PR? Or do it right after. Unsure.

**Comment by jef** [comment]
Let's merge #124 first!

**Comment by jef** [comment]
>  I'll give more attention to ordering in future contributions. The changes look good to me

I'm trying to find an option within `xo` or `prettier` to do this for us.

**Review by Doridian — APPROVED** [review]

**Pull request merged**
