### PR TITLE
chore(store): add 3070 to nvidia, best-buy-ca, newegg-ca

### PR DESCRIPTION
**Pull request by serg06**
### Description

Adds 3070 for:
- nvidia
- best-buy-ca
- newegg-ca

Let's get these 3070s!

### Testing

Just double-checked that the URLs work

### CODE REVIEW

**Comment by serg06** [comment]
Not sure why it lists 6 commits when I've only done two 🤷

**Comment by serg06** [comment]
Actually don't merge this in yet please, I'm going to add Newegg-ca real quick

**Comment by serg06** [comment]
Done!

**Review by jef — APPROVED** [review]

**Comment by jef** [comment]
Sweet! Looks good. I'll update the README.

**Comment by serg06** [comment]
Oh I totally forgot about the readme 😵

**Comment by jef** [comment]
No worries!

**Pull request merged**
