### PR TITLE
feat: webpage toggle, sound notification, fix evga links

### PR DESCRIPTION
**Pull request by Esg450**
### Description
feat: add sound notification ding
feat: toggle for opening webpage (good for if you're trying to run this on a VM or server)
fix: evga; add individual cards, rather than the whole search page for the 3080

### New dependencies
"play-sound": "^1.1.3",

### CODE REVIEW

**Comment by geman220** [comment]
I **heavily** suggest that the notification sound is https://www.youtube.com/watch?v=gjVmeKWOsEU

**Review by jef — CHANGES_REQUESTED** [review]
Not sure how I feel about putting `wav` files into GitHub. Perhaps we can `.gitignore` and point the users to a list of `wav`s in the wiki.

**Comment by jef** [comment]
Otherwise, great contribution. Thank you!

**Review by jef — APPROVED** [review]
Love it! Looks great! Thank you very much for all the work 😄

**Pull request merged**
