### PR TITLE
feat(store): adds models to bestbuy

### PR DESCRIPTION
**Pull request by pntless**
### Description

Adds 3080 xc3, ftw3, ftw3 ultra, aorus master, vision and 3090 ftw3, ftw3 ultra
Adds vision to readme list of models

### CODE REVIEW

**Comment by jef** [comment]
Any reason why you closed this out?

**Comment by pntless** [comment]
I'm new to github, still figuring it out... I realized it sent like 8 commits with this PR instead of just the two I wanted. I resubmitted.

**Comment by jef** [comment]
That's okay! They get squashed when I merge it in. Meaning, they get combined in all one in a pretty bow :)

**Comment by pntless** [comment]
Ahh good to know. Thanks for the tip :)

**Pull request closed without merging**
