### PR TITLE
feat(store): add newegg.ca

### PR DESCRIPTION
**Pull request by xdMatthewbx**
# Description

Adds newegg.ca to supported stores

Discord is xdMatthewbx#1337

### Testing

Tested running with `newegg-ca` added to stores list and am not encountering errors. Additionally stock alerts appear to be functioning but that may not be the case as none have actually come in stock yet.

### CODE REVIEW

**Review by gcssabbagh — COMMENTED** [review]
LGTM. Should we add .CA stores to the section in readme maybe?

**Comment by xdMatthewbx** [comment]
> LGTM. Should we add .CA stores to the section in readme maybe?

I believe I updated the readme to include newegg.ca

**Comment by geman220** [comment]
@xdMatthewbx since you are already in the `Readme.md` it might not be a terrible idea to add a note that this bot has the potential to use a lot of data, so people with data caps need to be mindful.  Someone posted a link of their [data usage](https://cdn.discordapp.com/attachments/756941548415090729/757603973090902026/unknown.png) in discord and it's upwards of 80GB

**Comment by gcssabbagh** [comment]
> > LGTM. Should we add .CA stores to the section in readme maybe?
> 
> I believe I updated the readme to include newegg.ca

Oh I'm stupid disregard my comment 🤦

**Comment by geman220** [comment]
Resolves #159 as a stop-gap until locales are implemented.

**Review by jef — APPROVED** [review]

**Comment by jef** [comment]
Thanks everyone!

**Pull request merged**
